name: surveysdb
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.10.14=0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.2.1=hf484d3e_1007
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1h=h7b6447c_0
  - python=3.7.4=h265db76_1
  - readline=7.0=h7b6447c_5
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - certifi==2020.12.5
    - pip==20.3.1
    - pony==0.7.14
    - setuptools==51.0.0
    - wheel==0.36.1
prefix: /home/bazsi/anaconda3/envs/surveysdb
